info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8080/eureka/
spring:
  cloud:
    config:
      uri: http://config:8080